CREATE DATABASE IF NOT EXISTS wardrobe_db;
USE wardrobe_db;

CREATE TABLE IF NOT EXISTS clothes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    image_path VARCHAR(255) DEFAULT NULL,
    category VARCHAR(50) NOT NULL,
    color VARCHAR(50) DEFAULT NULL,
    season VARCHAR(50) NOT NULL,
    occasion VARCHAR(50) NOT NULL,
    brand VARCHAR(100) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    favorite TINYINT(1) NOT NULL DEFAULT 0,
    wear_count INT NOT NULL DEFAULT 0,
    last_worn DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outfits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    occasion VARCHAR(50) DEFAULT NULL,
    season VARCHAR(50) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outfit_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    outfit_id INT NOT NULL,
    clothing_id INT NOT NULL,
    FOREIGN KEY (outfit_id) REFERENCES outfits(id) ON DELETE CASCADE,
    FOREIGN KEY (clothing_id) REFERENCES clothes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wear_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    clothing_id INT NOT NULL,
    worn_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (clothing_id) REFERENCES clothes(id) ON DELETE CASCADE
);
